[package]
name = "ntuple_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "visit", "extra-traits"] }
quote = "1.0"
ntuple = { path = "../ntuple" }

