[package]
name = "geometry3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
n_tuple = { path = "../n_tuple" }

